INSERT INTO PRODUCTOS_CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES (1, 'CATEGORIA 1');
INSERT INTO PRODUCTOS_CATEGORIA(ID_CATEGORIA, DESCRIPCION) VALUES (2, 'CATEGORIA 2');

INSERT INTO ROLES(ID_ROL, DESCRIPCION) VALUES (1, 'ROOT');
INSERT INTO ROLES(ID_ROL, DESCRIPCION) VALUES (2, 'ADMIN');
INSERT INTO ROLES(ID_ROL, DESCRIPCION) VALUES (3, 'USER');